# This workflow will install Python dependencies and run with a single version of Python

name: Scheduled Refresh of Data

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./src/requirements.txt ]; then pip install -r ./src/requirements.txt; fi
    
    - name: Run Python application
      run: |
        rm docs/state_wise_time_series_r0.csv
        python ./src/india_analysis.py
        jupyter nbconvert --ExecutePreprocessor.timeout=6000 --execute --output-dir='./docs' --to html "./src/RealtimeR0India.ipynb"
    
    - name: Commit file
      run: |
        git config --local user.email "khanparijat@gmail.com"
        git config --local user.name "Parijat29"
        git add -A -f
        git commit -m "Scheduled build output"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
