# This workflow will install Python dependencies and run with a single version of Python

name: Scheduled Refresh of Data

on:
  schedule:
    - cron:  '* */4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./src/requirements.txt ]; then pip install -r ./src/requirements.txt; fi
    - name: Run Python application
      run: |
        python ./src/india_analysis.py
    #    git add .
    #- name: Push to master branch
    #  uses: Automattic/action-commit-to-branch@master
    #  with:
    #    branch: 'master'
    #    commit_message: 'Scheduled Build'
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
